let updatedObject = {
  Sports: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Platform: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Racing: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Misc: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Shooter: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  "Role-Playing": {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Puzzle: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Simulation: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Action: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Fighting: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Adventure: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
  Strategy: {
    y: 0,
    count: 0,
    nasales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    eusales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    jpsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
    globalsales: { totalsales: 0, lowest: Number.POSITIVE_INFINITY, highest: 0 },
  },
};

//   export default updatedObject;
module.exports = { updatedObject };
